server {
    listen 80;
    server_name localhost;

    location / {
        # CHANGE THIS from /etc/nginx/html to /usr/share/nginx/html
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # This ensures your JS/CSS files are found correctly
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}